theme: jekyll-theme-cayman
title: App Harmony Playground
description: In quest of achieving true deployment isolation while architecting connected modular web applications that work together harmoniously as an enterprise hybrid mobile web application so that each connected modular application can manage their own software life cycles and release processes!
